import Head from 'next/head'
import Image from 'next/image'
import Socials from '../components/Socials';
import styles from '../styles/Home.module.css'

const Home = ({socials}) => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Next Js application</h2>
      <Socials socials={socials}/>
    </div>
  )
};

export const getStaticProps = async () => {
  // from env.local
  const res = await fetch(`${process.env.API_HOST}/socials`);
  const data = await res.json();
  if (!data) {
    return {
      notFound: true
    }
  }

  return {
    props: {
      socials: data
    }
  }
}

export default Home;